# Theme Settings
remote_theme           : "mmistakes/minimal-mistakes"  # Uncomment this line
minimal_mistakes_skin    : "default"

# Site Settings
locale                   : "en-US"
title                    : "Chang-Han Chen"  # Changed to match Jonas's style
title_separator          : "-"
name                     : "Chang-Han Chen"
description              : "Physics PhD at UC Berkeley working on quantum aspects of spacetime"
url                      : "https://Chang-Han-Chen.github.io"
repository               : "Chang-Han-Chen/Chang-Han-Chen.github.io"  # Added this

# Site Author
author:
  name             : "Chang-Han Chen"
  avatar           : "/assets/images/bio-photo.jpg"  # Add your photo here
  bio              : "Physics PhD at UC Berkeley. I work on quantum aspects of spacetime."
  location         : "Berkeley, CA"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:changhanc@berkeley.edu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Chang-Han-Chen"

# Navigation
main:
  - title: "About"
    url: /
  - title: "Publications"
    url: /publications/
  - title: "Resume"
    url: /resume/
  - title: "Blog"
    url: /blog/

# Defaults
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: false  # Changed to false to match academic style
      related: true

# Reading Files
include:
  - _pages

# Remove unnecessary plugins and keep essential ones
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
