# Theme Settings
#remote_theme           : "mmistakes/minimal-mistakes"  # Uncomment this line
minimal_mistakes_skin    : "air"

# Site Settings
locale                   : "en-US"
title                    : "Chang-Han Chen"  # Changed to match Jonas's style
title_separator          : "-"
name                     : "Chang-Han Chen"
description              : "Physics PhD at UC Berkeley working on quantum aspects of spacetime"
url                      : "https://Chang-Han-Chen.github.io"
repository               : "Chang-Han-Chen/Chang-Han-Chen.github.io"  # Added this

# Site Author
author:
  name             : "Chang-Han Chen"
  avatar           : # Add your photo here
  bio              : "Physics PhD at UC Berkeley. I work on quantum aspects of spacetime."
  location         : "Berkeley, CA"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:changhanc@berkeley.edu"

permalink: /:categories/:title/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Pagination with jekyll-paginate
paginate: 5 # amount of posts to show
paginate_path: /page:num/


# Defaults
enable_copy_code_button: true

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: false  # Changed to false to match academic style
      related: true
      show_date: true
      comments: false

# Reading Files
include:
  - _pages

# Remove unnecessary plugins and keep essential ones
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
